---
title: Removes the drive letter from the EFI partition.
description: This happens after clean install without formatting the drive
actions:
  - !powerShell:
    command: |
     $efiPartition = Get-Partition -DiskNumber 0 -PartitionNumber 1
      Remove-PartitionAccessPath -Partition $efiPartition -AccessPath $efiPartition.DriveLetter + ":\"
    wait: true
    runas: currentUserElevated
